### ISSUE TITLE
Still creates advanced-cache.php

### ISSUE THREAD

**Issue by deargeek** [wp-media/wp-rocket-helpers#14]
When activated the WP Rocket code still appears in wp-content/advanced-cache.php

This prevents other caches, like WPMUDEV Hummingbird from working.

**Comment by arunbasillal** [comment]
WP Rocket required `advanced-cache.php` to work. If you meant, `deactivated`, and if WP Rocket did not remove itself from advanced-cache.php, then please remove it manually. 

Please note that this is a repo for WP Rocket helper plugins and not for product help. For support, please use our support channels - https://wp-rocket.me/support/

**Comment by deargeek** [comment]
This helper is supposed to disable WP Rocket caching. Surely if WP Rocket is not caching it does not need to be in advanced-cache.php?

**Comment by girlie** [comment]
There are multiple helper plugins in this repo -- so, if you're referring to this one:
https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-no-cache

...then all it does is add a filter to prevent the cache files from being generated -- it does not also eliminate the need for WP Rocket to use the _advanced-cache.php_ file (because it still relies on the contents of this file to execute its other features).

And FWIW, WP Rocket should not be used at the same time as other caching plugins anyway:
https://docs.wp-rocket.me/article/73-is-wp-rocket-compatible-with-others-cache-plugins-like-wp-super-cache-or-w3-total-cache
